service: card-tokenization

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  createToken:
    handler: src/handlers/create-token.handler
    events:
      - http:
          path: token
          method: post

  getTokenData:
    handler: src/handlers/get-token-data.handler
    events:
      - http:
          path: token/{token}
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    port: 3000
    